In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from pathlib import Path
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [5]:
from pathlib import Path

In [6]:
import pandas as pd

In [7]:
project_dir = Path().resolve()

In [8]:
data_path = project_dir/"Data/household_energy_consumption.csv"

In [9]:
df = pd.read_csv(data_path,parse_dates=['Date'])

In [10]:
df.dtypes

Date                      datetime64[ns]
Energy_Consumption_kWh           float64
Household_Size                     int64
Avg_Temperature_C_x              float64
Has_AC                             int64
Peak_Hours_Usage_kWh             float64
Avg_Temperature_C_y              float64
Avg_Humidity_Pct                   int64
Day                                int64
Month                              int64
Is Weekend                         int64
Is_Holiday                         int64
dtype: object

In [11]:
df.sort_values(by='Date')

,Date,Energy_Consumption_kWh,Household_Size,Avg_Temperature_C_x,Has_AC,Peak_Hours_Usage_kWh,Avg_Temperature_C_y,Avg_Humidity_Pct,Day,Month,Is Weekend,Is_Holiday
0,2025-01-04,8.4,4,17.8,0,3.2,12.0,80,5,1,1,0
8565,2025-01-04,7.6,3,18.2,0,2.7,12.0,80,5,1,1,0
8566,2025-01-04,18.8,5,16.8,1,7.8,12.0,80,5,1,1,0
8567,2025-01-04,12.0,5,14.7,0,3.8,12.0,80,5,1,1,0
8568,2025-01-04,4.4,2,15.9,0,1.5,12.0,80,5,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
78389,2025-07-04,7.4,3,14.7,0,2.8,19.6,75,4,7,0,1
78390,2025-07-04,5.9,2,14.2,0,2.1,19.6,75,4,7,0,1
78391,2025-07-04,15.1,6,18.1,0,5.9,19.6,75,4,7,0,1
78379,2025-07-04,7.0,3,17.8,0,2.5,19.6,75,4,7,0,1
80873,2025-07-04,6.0,2,18.7,1,3.0,19.6,75,4,7,0,1

In [12]:
df.isnull().sum()

Date                      0
Energy_Consumption_kWh    0
Household_Size            0
Avg_Temperature_C_x       0
Has_AC                    0
Peak_Hours_Usage_kWh      0
Avg_Temperature_C_y       0
Avg_Humidity_Pct          0
Day                       0
Month                     0
Is Weekend                0
Is_Holiday                0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(2570)

In [14]:
duplicates = df[df.duplicated()]

In [15]:
len(duplicates)/len(df)

0.03177782723743106

In [16]:
duplicates.sort_values(by='Energy_Consumption_kWh',ascending=False)

,Date,Energy_Consumption_kWh,Household_Size,Avg_Temperature_C_x,Has_AC,Peak_Hours_Usage_kWh,Avg_Temperature_C_y,Avg_Humidity_Pct,Day,Month,Is Weekend,Is_Holiday
80761,2025-07-04,20.0,6,18.4,1,9.7,19.6,75,4,7,0,1
80549,2025-07-04,20.0,5,15.7,1,8.2,19.6,75,4,7,0,1
400,2025-01-04,20.0,6,18.1,1,9.9,12.0,80,5,1,1,0
972,2025-01-04,20.0,6,16.6,1,8.9,12.0,80,5,1,1,0
80400,2025-07-04,20.0,6,18.0,1,9.4,19.6,75,4,7,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2907,2025-01-04,0.5,1,17.4,0,0.2,12.0,80,5,1,1,0
62744,2025-05-04,0.5,1,13.9,0,0.2,14.3,78,6,5,1,0
1915,2025-01-04,0.5,1,18.2,0,0.2,12.0,80,5,1,1,0
2587,2025-01-04,0.5,1,15.2,0,0.2,12.0,80,5,1,1,0
78120,2025-07-04,0.5,1,18.0,0,0.2,19.6,75,4,7,0,1

In [17]:
(df.drop_duplicates(inplace=True,ignore_index=True))

In [18]:
df.drop(columns=['Date','Energy_Consumption_kWh','Avg_Temperature_C_y'],inplace=True)

In [19]:
df

,Household_Size,Avg_Temperature_C_x,Has_AC,Peak_Hours_Usage_kWh,Avg_Humidity_Pct,Day,Month,Is Weekend,Is_Holiday
0,4,17.8,0,3.2,80,5,1,1,0
1,5,20.1,1,7.8,80,5,1,1,0
2,3,12.7,0,3.1,80,5,1,1,0
3,5,15.1,1,7.2,80,5,1,1,0
4,2,21.9,0,1.8,80,5,1,1,0
...,...,...,...,...,...,...,...,...,...
78299,4,14.9,1,6.4,75,4,7,0,1
78300,5,17.5,1,8.1,75,4,7,0,1
78301,4,16.9,1,6.3,75,4,7,0,1
78302,4,18.2,1,6.6,75,4,7,0,1
78303,2,18.7,1,3.0,75,4,7,0,1

In [20]:
splix_idx=int(len(df)*0.8)

In [21]:
splix_idx

62643

In [22]:
features = df.drop(columns=['Peak_Hours_Usage_kWh'])

In [23]:
features

,Household_Size,Avg_Temperature_C_x,Has_AC,Avg_Humidity_Pct,Day,Month,Is Weekend,Is_Holiday
0,4,17.8,0,80,5,1,1,0
1,5,20.1,1,80,5,1,1,0
2,3,12.7,0,80,5,1,1,0
3,5,15.1,1,80,5,1,1,0
4,2,21.9,0,80,5,1,1,0
...,...,...,...,...,...,...,...,...
78299,4,14.9,1,75,4,7,0,1
78300,5,17.5,1,75,4,7,0,1
78301,4,16.9,1,75,4,7,0,1
78302,4,18.2,1,75,4,7,0,1
78303,2,18.7,1,75,4,7,0,1

In [24]:
target = features = df['Peak_Hours_Usage_kWh']

In [25]:
def load_data(path):
    """Loading the data and Processing"""
    df = pd.read_csv(path,parse_dates=['Date'])
    df.drop_duplicates(inplace=True,ignore_index=True)
    df.drop(columns=['Date','Energy_Consumption_kWh','Avg_Temperature_C_y'],inplace=True)
    features = df.drop(columns=['Peak_Hours_Usage_kWh'])
    target = df['Peak_Hours_Usage_kWh']
    splix_idx=int(len(df)*0.8)
    X_train = features.iloc[:splix_idx]
    y_train = target.iloc[:splix_idx]
    X_test = features.iloc[splix_idx:]
    y_test = target.iloc[splix_idx:]
    return {
        "X_train":X_train,
        "y_train":y_train,
        "X_test":X_test,
        "y_test":y_test,
        "features":features,
        "target":target
    }

In [26]:
bundled_data=load_data(data_path)

In [27]:
X_train= bundled_data['X_train']
y_train = bundled_data['y_train']
X_test= bundled_data['X_test']
y_test = bundled_data['y_test']
features = bundled_data['features']
target=bundled_data['target']

In [28]:
X_train

,Household_Size,Avg_Temperature_C_x,Has_AC,Avg_Humidity_Pct,Day,Month,Is Weekend,Is_Holiday
0,4,17.8,0,80,5,1,1,0
1,5,20.1,1,80,5,1,1,0
2,3,12.7,0,80,5,1,1,0
3,5,15.1,1,80,5,1,1,0
4,2,21.9,0,80,5,1,1,0
...,...,...,...,...,...,...,...,...
62638,4,17.4,1,78,2,6,0,0
62639,1,15.8,1,78,2,6,0,0
62640,3,20.1,0,78,2,6,0,0
62641,1,14.8,1,78,2,6,0,0
62642,1,20.7,0,78,2,6,0,0

In [29]:
new_model = RandomForestRegressor(n_estimators=400, max_depth=3)

In [30]:
features

,Household_Size,Avg_Temperature_C_x,Has_AC,Avg_Humidity_Pct,Day,Month,Is Weekend,Is_Holiday
0,4,17.8,0,80,5,1,1,0
1,5,20.1,1,80,5,1,1,0
2,3,12.7,0,80,5,1,1,0
3,5,15.1,1,80,5,1,1,0
4,2,21.9,0,80,5,1,1,0
...,...,...,...,...,...,...,...,...
78299,4,14.9,1,75,4,7,0,1
78300,5,17.5,1,75,4,7,0,1
78301,4,16.9,1,75,4,7,0,1
78302,4,18.2,1,75,4,7,0,1
78303,2,18.7,1,75,4,7,0,1

In [31]:
new_model.fit(X_train,y_train)

RandomForestRegressor(max_depth=3, n_estimators=400)

In [32]:
new_predict = new_model.predict(X_test)

In [33]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error

In [34]:
print(f"MSE {mean_squared_error (y_test,new_predict)}")
print(f"MAE {mean_absolute_error (y_test,new_predict)}")
print(f"r2 {r2_score (y_test,new_predict)}")
print(f"RMSE {root_mean_squared_error (y_test,new_predict)}")

MSE 0.6027520973344672
MAE 0.617511523848169
r2 0.9029798410954328
RMSE 0.7763711079982737

In [35]:
# def objective(trial):
#     params = {
#         "n_estimators": trial.suggest_int("n_estimators", 200, 1000,steps=100),
#         "max_depth": trial.suggest_int("max_depth", 4, 10),
#         "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
#         "subsample": trial.suggest_float("subsample", 0.7, 1.0),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.7, 1.0),
#         "gamma": trial.suggest_float("gamma", 0, 2),
#         "min_child_weight": trial.suggest_int("min_child_weight", 1, 5),
#         "reg_alpha": trial.suggest_float("reg_alpha", 0, 1),
#         "reg_lambda": trial.suggest_float("reg_lambda", 0, 3),
#     }
#     model=XGBRegressor(**params)

#     scores = cross_val_score(model,X_train,y_train, cv=5,scoring="neg_root_mean_squared_error",n_jobs=-1)

#     return scores.mean()

In [36]:
import optuna
from sklearn.model_selection import cross_val_score

c:\Users\Shaaf\Desktop\Data Science\Practice Projects\DeepLearning\Energy Predictions\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [37]:
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 1000),
        "max_depth": trial.suggest_int("max_depth", 4, 10),
        "min_samples_split": trial.suggest_float("min_samples_split", 0.7, 1.0),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "random_state": 42,
        "n_jobs": -1
    }
    model=RandomForestRegressor(**params)

    scores = cross_val_score(model,X_train,y_train, cv=5,scoring="neg_root_mean_squared_error",n_jobs=-1)

    return scores.mean()

In [38]:
# study = optuna.create_study(direction="minimize")

# study.optimize(
#     objective,
#     n_trials=100,
#     show_progress_bar=True
# )

In [39]:
# print("Best RMSE:", study.best_value)

# print("Best Parameters:")
# print(study.best_params)

In [55]:
xgb_model = XGBRegressor(**grid_search.best_params_)

In [56]:
xgb_model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=800,
             n_jobs=None, num_parallel_tree=None, ...)

In [45]:
from sklearn.model_selection import GridSearchCV

In [60]:
params={
    "n_estimators":[800,1000,1200,1600],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.8, 1.0]
}

In [61]:
model = XGBRegressor()

In [62]:
grid_search = GridSearchCV(estimator=model, param_grid=params,scoring="r2",cv=5, n_jobs=-1, verbose=1)

In [63]:
grid_search.fit(X_train,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7],
                         'n_estimators': [800, 1000, 1200, 1600],
                         'subsample': [0.8, 1.0]},
             scoring='r2', verbose=1)

In [65]:
grid_search.best_params_

{'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 800, 'subsample': 0.8}

In [57]:
xgb_predicted = xgb_model.predict(X_test)

In [58]:
print(f"MSE {mean_squared_error (y_test,xgb_predicted)}")
print(f"MAE {mean_absolute_error (y_test,xgb_predicted)}")
print(f"r2 {r2_score (y_test,xgb_predicted)}")
print(f"RMSE {root_mean_squared_error (y_test,xgb_predicted)}")

MSE 0.44930074884281823
MAE 0.5316283454734256
r2 0.9276796708938162
RMSE 0.6702989995836323